config/routes.rb
Cvmaker::Application.routes.draw do
  root :to => "resumes#index"

  resources :resumes do
    post 'clone', :as => 'clone' 
  end

  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'

  get 'authenticate' => 'authenticate#index'
  get 'authenticate/callback' => 'authenticate#callback'
  get 'authenticate/logout' => 'authenticate#logout'

end

app/models/mercury/image.rb
class Mercury::Image < ActiveRecord::Base

  self.table_name = :mercury_images

  attr_accessible :image

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" },
        :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
        :url => "/system/:attachment/:id/:style/:filename"

  delegate :url, :to => :image

  def serializable_hash(options = nil)
    options ||= {}
    options[:methods] ||= []
    options[:methods] << :url
    super(options)
  end

end

app/models/resume.rb
class Resume < ActiveRecord::Base
  attr_accessible :content, :name, :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authenticate_controller.rb
require 'rubygems'

require 'linkedin'

class AuthenticateController < ApplicationController

  def index
    # get your api keys at https://www.linkedin.com/secure/developer
    client = LinkedIn::Client.new("752cqogua16ta5", "ZfzS2s2KTFJdgz04")
    request_token = client.request_token(:scope => "r_basicprofile+r_fullprofile+r_emailaddress+r_contactinfo", :oauth_callback =>
                                      "http://#{request.host_with_port}/authenticate/callback")
    session[:rtoken] = request_token.token
    session[:rsecret] = request_token.secret

    redirect_to client.request_token.authorize_url

  end

  def callback
    client = LinkedIn::Client.new("752cqogua16ta5", "ZfzS2s2KTFJdgz04")
    if session[:atoken].nil?
      pin = params[:oauth_verifier]
      atoken, asecret = client.authorize_from_request(session[:rtoken], session[:rsecret], pin)
      session[:atoken] = atoken
      session[:asecret] = asecret
    else
      client.authorize_from_access(session[:atoken], session[:asecret])
    end
    
    @profile = client.profile(:fields => ['interests', 'certifications', 'email-address', 'main-address', 'phone-numbers', 'first-name', 'last-name', 'headline', 'positions', 'educations'])
    @phone = @profile.phone_numbers.all.first.phone_number
    @email = @profile.email_address
    @address = @profile.main_address
    @educations = @profile.educations.all
    @positions = @profile.positions.all
    @certifications = @profile.certificates
    @interests = @profile.interests

    html = render_to_string 
  	
  	new_record = Resume.new
    new_record.content = html
    new_record.save
    
    redirect_to "/editor/resumes/" + new_record.id.to_s
  end

  def logout
  	session.clear
  	redirect_to root_path
  end
end

app/controllers/mercury/images_controller.rb
class Mercury::ImagesController < MercuryController

  respond_to :json

  # POST /images.json
  def create
    @image = Mercury::Image.new(params[:image])
    @image.save
    respond_with @image
  end

  # DELETE /images/1.json
  def destroy
    @image = Mercury::Image.find(params[:id])
    @image.destroy
    respond_with @image
  end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  # GET /resumes
  # GET /resumes.json
  def index
    #binding.pry
    @resumes = Resume.first(5)

    @community_resumes = Resume.where(:category != "sample")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resumes }
    end
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
    @resume = Resume.find(params[:id])

    # We will worry about the pdf export later on. lets just get the flow and linkedin right right now
    #binding.pry
    #@resume[:content] = externals_to_absolute_path(@resume[:content])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resume }
      format.pdf do
        render pdf: "resume.pdf", template: "resumes/show.html.erb"
      end
    end
  end

  # GET /resumes/new
  # GET /resumes/new.json
  def new
    @resume = Resume.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resume }
    end
  end

  # GET /resumes/1/edit
  def edit
    @resume = Resume.find(params[:id])
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(params[:resume])

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render json: @resume, status: :created, location: @resume }
      else
        format.html { render action: "new" }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resumes/1
  # PUT /resumes/1.json
  def update
    @resume = Resume.find(params[:id])

    @resume.content = params[:content][:page_content][:value]  
    @resume.category = ""
    @resume.save!

    render text: ""

=begin
    respond_to do |format|
      if @resume.update_attributes(params[:resume])
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
=end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy

    respond_to do |format|
      format.html { redirect_to resumes_url }
      format.json { head :no_content }
    end
  end

  def clone 
    template = Resume.find(params[:resume_id])

    new_record = template.dup
    new_record.save
    
    redirect_to "/editor/resumes/" + new_record.id.to_s
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def monthname(monthnumber)  
	    if monthnumber  
	        Date::MONTHNAMES[monthnumber]  
	    end  
	end 
end

app/helpers/authenticate_helper.rb
module AuthenticateHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/authenticate/callback.html.erb
<title>My CV</title>
<link rel="stylesheet" type="text/css" href="/assets/themes/metro.css">
<div id="main">
   <h1 id="title"><%=@profile.first_name%>&nbsp;<%=@profile.last_name%></h1>
   <div class="basic-info section">
      <h2 class="title">Contact</h2>
      <div class="set">
         <p class="address">
            <span class="value">
            <%=@address%>				</span>
         </p>
         <div class="r">
            <p class="email"><label>E-mail<span class="colon">:</span></label>&nbsp;<%=@email if @email%><span class="value"></span></p>
            <p class="phone"><label>Phone<span class="colon">:</span></label>&nbsp;<%=@phone if @phone%><span class="value"></span></p>
         </div>
         <div class="clear"> </div>
      </div>
      <!-- set //-->
      <div class="clear"> </div>
   </div>
   <!-- basic-info //-->
   <div class="section section-work">
      <h2 class="title">Work experience</h2>
      <div class="set">
         <% @positions.each do |position| %>
            <div class="item">
               <h3><span class="company l"><%= position.company.name %></span>
                  <span class="date r"><%= monthname(position.start_date.month) if position.start_date %>,  <%= position.start_date.year if position.start_date %> — <%= monthname(position.end_date.month) if position.end_date %>  <%= "," + position.end_date.year.to_s if position.end_date %> <%= "present" unless position.end_date %></span>
               </h3>
               <span class="clear"> </span>
               <span class="job_title"><%= position.title %></span><span class="info"><%= position.summary %></span><span class="clear"> </span>
            </div>
         <% end %>
      </div>
      <div class="clear"> </div>
   </div>
   <!--div class="section section-references">
      <h2 class="title">References</h2>
      <div class="set">
         <div class="item">
            <span class="info">Referenced: Dr. Neena Goveas</span>
         </div>
      </div>
      <div class="clear"> </div>
   </div-->
   <div class="section section-education">
      <h2 class="title">Education</h2>
      <div class="set">
         <% @educations.each do |education| %>
            <div class="item">
               <h3><span class="course l"><%= education.degree %></span>
                  <span class="date r"><%= education.start_date.year if education.start_date %> — <%= education.end_date.year if education.end_date %></span>
               </h3>
               <span class="clear"> </span>
               <span class="school">Bits Pilani</span><span class="info"><%= education.field_of_study %> from <%= education.school_name %></span><span class="clear"> </span>
            </div>
         <% end %>
      </div>
      <div class="clear"> </div>
   </div>
   <div class="section section-interests">
      <h2 class="title">Interests</h2>
      <div class="set">
         <div class="item">
            <span class="info"><%= @interests if @interests %></span>
         </div>
      </div>
      <div class="clear"> </div>
   </div>
   <div class="section section-1390552807382">
      <h2 class="title">Custom Content</h2>
      <div class="set">
         <div class="item">
            <span class="info">This is some custom content.</span>
         </div>
      </div>
      <div class="clear"> </div>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cvmaker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury' %>
    <%= javascript_include_tag 'jquery-1.7', 'mercury' %>
  </head>
  <body>
    <script type="text/javascript">
      // Set to the url that you want to save any given page to, leave null for default handling.
      var saveUrl = null;

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveStyle:  null, // 'form', or 'json' (default json)
        saveMethod: null, // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });
    </script>
  </body>
</html>

app/views/resumes/_form.html.erb
<%= form_for(@resume) do |f| %>
  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing resume</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<head>
    <!-- Custom Google Web Font -->
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
</head>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Resumefy</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#createResume"><i class="fa fa-magic fa-fw"> </i> Create from Scratch</a>
                    </li>
                    <li><a href="/authenticate"><i class="fa fa-linkedin fa-fw"> </i> Connect with LinkedIn</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="intro-header">

        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Resumefy</h1>
                        <h3>Create Beautiful Resumes</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li><a href="#createResume" class="btn btn-default btn-lg"><i class="fa fa-magic fa-fw"></i> <span class="network-name">
                                Create from scratch</span></a>
                            </li>
                            <li><a href="/authenticate" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">connect with Linkedin</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <div class="content-section-a">

        <div class="container">

            <div class="row" id="createResume">
                <div class="col-lg-5 col-sm-6">
                    <h2 class="section-heading">Many awesome templates</h2>
                    <p class="lead">Resumefy is built for a unique breed of professionals. So why should your resume look like the same as everyone else? <br> <br>Choose from 5 beautiful templates to get started.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <div class="clearfix"></div>
                    <table class="table">
                      <tbody>
                          <thead>
                            <tr>
                              <th>Customizable Templates</th>
                              <th></th>
                              <th></th>
                            </tr>
                          </thead>
                          <% @resumes.each do |resume| %>
                          <tr>
                            <td><%= resume.name %></td>
                            <td><%= link_to 'Preview', resume, target: "_blank" %></td>
                            <td><%= link_to 'Use This', resume_clone_path(resume), method: :post %></td>
                          </tr>
                          <% end %>
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Direct Import from LinkedIn</h2>
                    <p class="lead">Everything is automated these days, from coffee machines all the way up to cars!?<br><br> Automatically turn your existing LinkedIn profile into a beatiful and functional resume in a matter of seconds.</p>
                    <p class="lead">P.S. We respect your privacy. We will never post on behalf of you.</p>
                    <a href="/authenticate" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Connect from LinkedIn</span></a>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="/assets/clock.png" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Export as a PDF file</h2>
                    <p class="lead">What good is a cow that gives no milk? Or a resume building website, that doesnt give you a resume? <br><br>Download your finished resumes as a PDF file for easiliy sharing it with all the <i>right</i> companies.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="/assets/cert.png" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>Beautify your resume:</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li><a href="#createResume" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Create new</span></a>
                        </li>
                        <li><a href="/authenticate" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">connect Linkedin</span></a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!--ul class="list-inline">
                        <li><a href="#home">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#about">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#services">Services</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#contact">Contact</a>
                        </li>
                    </ul-->
                    <p class="copyright text-muted small">Copyright &copy; Shubham 2013. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- JavaScript -->
    <script src="/assets/jquery-1.10.2.js"></script>
    <script src="/assets/bootstrap.js"></script>

app/views/resumes/new.html.erb
<h1>New resume</h1>

<%= render 'form' %>

<%= link_to 'Back', resumes_path %>

app/views/resumes/show.html.erb
<div class="content">
<div id="page_content" class="mercury-region" data-mercury="full">
  <%= raw @resume.content %>
</div>
</div>

<form style="position:relative; left: 50%;" class="no-print">
	<input type="button" value="Print this page" onClick="window.print()">
</form>

app/views/resumes/show.pdf.html.erb
<div class="content">
<div id="page_content" class="mercury-region" data-mercury="full">
  <%= raw @resume.content %>
</div>
</div>